version: "3.7"
services:   
  server:        
    build: ./server      
    ports:            
      - "5000:5000"  
    restart: always
    volumes:            
      - json_data:/usr/src/app/data
    command: npm run start

  client:        
    build: ./client        
    ports:            
      - "8080:8080"
    links:
      - server
    command: npm run start

volumes:
  json_data:

 
